### ISSUE TITLE
Policy crashes audit-scanner

### ISSUE THREAD

**Issue by mueller-ma** [kubewarden/allowed-proc-mount-types-psp-policy#57]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The following policy crashes the audit-scanner (I removed some fields like metadata and namespaceSelector):

````yaml

apiVersion: policies.kubewarden.io/v1
kind: ClusterAdmissionPolicy
spec:
  backgroundAudit: true
  mode: protect
  module: registry://ghcr.io/kubewarden/policies/allowed-proc-mount-types-psp:v0.1.9
  mutating: false
  policyServer: default
  rules:
  - apiGroups:
    - ""
    apiVersions:
    - v1
    operations:
    - CREATE
    resources:
    - pods
    - pods/ephemeralcontainers
  - apiGroups:
    - ""
    apiVersions:
    - v1
    operations:
    - UPDATE
    resources:
    - pods
    - pods/ephemeralcontainers
  settings: {}
  timeoutSeconds: 10
````

Log from audit scanner:
````
{"level":"info","RunUID":"74252385-2dd0-43bb-bbff-eee72855ff61","time":"2024-07-08T13:44:17Z","message":"clusterwide resources scan started"}
{"level":"fatal","error":"no matches for /v1, Resource=pods/ephemeralcontainers","time":"2024-07-08T13:44:17Z","message":"Error on cmd.Execute()"}
````

The crash should be fixed by https://github.com/kubewarden/audit-scanner/issues/307, but the policy is still invalid.

### Expected Behavior

The policy should be valid.

### Environment

```markdown
- OS: Linux
- Architecture: arm64
- Kubernetes: v1.28.10+rke2r1
```
